server {
    listen 80;
    server_name sovietgram.su www.sovietgram.su;

    client_max_body_size 110m;

    location /static/ {
        alias /opt/sovietgram/var/static/;
        access_log off;
        expires -1;
        add_header Cache-Control "no-cache, must-revalidate";
    }

    location ^~ /media/messages/ {
        return 404;
    }

    location /media/ {
        alias /opt/sovietgram/var/media/;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://127.0.0.1:8000;
    }
}
