# Generated by Django 5.1 on 2026-09-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_archive_preferences"),
        ("messenger", "0005_chat_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="history_visible_to_new_members",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="members_can_send_messages",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="members_can_send_media",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="members_can_send_links",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="members_can_add_members",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chat",
            name="members_can_pin_messages",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chat",
            name="slow_mode_seconds",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chat",
            name="signatures_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="can_see_pre_join_history",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ChatInviteLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=64)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("usage_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("chat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invite_links", to="messenger.chat")),
                ("creator", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_chat_invite_links", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="ChatAdminLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="chat_admin_actions", to=settings.AUTH_USER_MODEL)),
                ("chat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="admin_log", to="messenger.chat")),
                ("target_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="chat_admin_actions_targeting", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at", "-id")},
        ),
    ]
