# Generated by Django 5.1 on 2026-09-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0006_community_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatparticipant",
            name="cleared_before_message_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="is_hidden",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name="MessageHiddenForUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_for_users",
                        to="messenger.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "user"),
                        name="unique_hidden_message_for_user",
                    )
                ],
            },
        ),
    ]
