# Generated by Django 5.2 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0007_telegram_deletion_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="special_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="message",
            name="special_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Обычное сообщение"),
                    ("poll", "Опрос"),
                    ("todo", "Список задач"),
                    ("article", "Статья"),
                    ("location", "Геопозиция"),
                ],
                db_index=True,
                default="",
                max_length=16,
            ),
        ),
    ]
